### PR TITLE
Added MeteorObservables and MongoObservables wrappers with RxJS

### PR DESCRIPTION
**Pull request by dotansimha**
@Urigo 

Usage example for Collection and Cursor:
```
let collection = new MongoObservable.Collection("test");
let ob : Observable = collection.find({});
ob.subscribe((col) => {
   console.log("new data:", col);
});
```

And then in the View:
```
<div *ngFor="let item of ob | async"></div>
```

Usage example for Meteor.call:
```
MeteorObservable.call("myMethod").subscribe((response) => {
   console.log("server response:", response);
}, (error : Meteor.Error) => {
   console.log("Error!", error);
});
```

Usage example for Meteor.subscribe:
```
MeteorObservable.subscribe("myMethod").subscribe(() => {
   console.log("ready!");
}, (error : Meteor.Error) => {
   console.log("Error!", error);
});
```

### CODE REVIEW

**Comment by Tallyb** [comment]
@dotansimha  wow! Will that work in a service and reflected in a component?

**Comment by Urigo** [comment]
@Hongbo-Miao @barbatus @kamilkisiela

**Comment by dotansimha** [comment]
@Tallyb Yeah, you can also use `ngrx` to manage your application flow and put the subscriptions in a service instead of the Component. 

@Urigo do you think we should add this as default when using `MeteorComponent`? (the `call` and `subscribe`).

**Comment by Hongbo-Miao** [comment]
@dotansimha how can I import `MeteorObservable`, `MongoObservable`? Thanks

**Comment by Hongbo-Miao** [comment]
@dotansimha after I add
```
import { MongoObservable } from 'angular2-meteor';
export const Tests = new MongoObservable.Collection('test');
```
It give me error in my terminal and crash my server:
> Error: Cannot find module 'meteor/mongo'

**Comment by kamilkisiela** [comment]
@dotansimha No more Cursor :fire: Nice job!

**Comment by dotansimha** [comment]
@Hongbo-Miao 
That's weird. which version of Meteor do you use?
Also, can you share the project so I can try it locally? 
I took the angular2-meteor-boilerplate and tried with it, and it works great (the imports). 

I can also try to remove the imports from the code, but it will mean that we depend on Meteor's globals and I do not want to.

**Comment by dotansimha** [comment]
@Hongbo-Miao 
Also, take a look in here: https://github.com/dotansimha/angular2-meteor-with-observables
This is a simple example for usage, and it works great...

**Comment by dotansimha** [comment]
@Hongbo-Miao @Tallyb @Urigo @kamilkisiela 
I need your advice about the usage of `call` and `subscribe`. 
At the moment, when you use those methods, you get in response the RxJS `Observable`, which does not run the actual Meteor method with subscribing to the result.
That means, if you use it like this:

```
MeteorObservable.call("...");
MeteorObservable.subscribe("...");
```

It would never execute the Meteor method or subscription, instead, you must register to the data as a subscriber:
```
MeteorObservable.call("...").subscribe((res) => {}, (err) => {});
MeteorObservable.subscribe("...").subscribe((res) => {}, (err) => {});
```

As a solution, I can subscribe to the `Observable` before it returns from the method call, and it will  make sure that the method actually called without any subscription. 

What do you think?

**Comment by dotansimha** [comment]
@Hongbo-Miao The imports issue fixed in #20df9803cac8ee0ad3a4014bd66ed965a5938165.

**Comment by Tallyb** [comment]
@dotansimha  assuming you will do the subscribe to the observable yourself, what would the call look like? 
`Meteor.observable.call ("myMethod", (res)=>{}, (err)=>{}) `
If so, I am in favor of the original way: `.subscribe`.

**Comment by Hongbo-Miao** [comment]
@dotansimha how to unsubscribe a `Meteor.SubscriptionHandle` now? I didn't get it [here](https://github.com/Urigo/angular2-meteor/pull/358/files#diff-66618d457a50f4ee0cd9f21feb2547b7R53).

**Comment by Hongbo-Miao** [comment]
@dotansimha is there a way to unsubscribe a `Meteor.SubscriptionHandle` now? I didn't get it [here](https://github.com/Urigo/angular2-meteor/pull/358/files#diff-66618d457a50f4ee0cd9f21feb2547b7R53).

If not, maybe add something like `MeteorObservable.unsubscribe('products')`?

**Comment by barbatus** [comment]
On usage in `MeteorComponent`. We could think actually here about a different approach we already talked about: splitting MeteorComponent. 

One way to implement it could be to have, for example, a `CallObservable` annotation and `ICallObservable` interface, so one could use it as:
```ts
@CallObservable()
class MyComponent implements ICallObservable {
  click() {
     this.call(...).subscribe(...);
  }
}
```

**Comment by barbatus** [comment]
@dotansimha linter seems to throw a bunch of errors, do you mind to fix? )

**Comment by dotansimha** [comment]
@Hongbo-Miao , the `ngrx` branch still need some modifications and fixes, because I try to implement it with `effects` package. 
Note that the line you mentioned in the code will work with `ngrx` because of you use `effects` it will execute and subscribe to the data, for example:

```
  @Effect() subscribeProducts$ = this.updates$
    .whenAction(ProductsActions.CALL_SUBSCRIBE_PRODUCTS)
    .switchMap(() => this.productsService.subscribeProducts())
    .map(() => ({type: ProductsActions.LOAD_PRODUCTS_FROM_COLLECTION}));

  @Effect() loadProducts$ = this.updates$
    .whenAction(ProductsActions.LOAD_PRODUCTS_FROM_COLLECTION)
    .switchMap(() => this.productsService.getProducts())
    .map(products => ({type: ProductsActions.PRODUCTS_COLLECTION_UPDATED, payload: products}));
```

So in that case, the `CALL_SUBSCRIBE_PRODUCTS` uses the subscription and when it's ready it dispatch the `LOAD_PRODUCTS_FROM_COLLECTION` which return an `Observable` with the data, and each time the data changes, the `PRODUCTS_COLLECTION_UPDATED` called. 

If you don't use `ngrx`, you will need to subscribe to the data by your self (if you use `ngFor` with `async` pipe you won't need).

The subscription handler of Meteor subscribe is inside the Observable you get, and when you dispose or unsubscribe, it will automatically close the Meteor subscription. 
So if you use `ngFor` to display the data, and you hide the `ngFor` using `ngIf` - the subscription will close it self and reopened when needed. 
Also, when the Component destroyed it will close the subscription. 

Regarding the `Tracker.autorun`, can you provide a use case and I will try to find a solution? 

Thanks.

**Comment by dotansimha** [comment]
@barbatus Fixed!

**Comment by dotansimha** [comment]
@Hongbo-Miao , I fixed the `ngrx` branch and added example for `call` and example for iterating using `ngFor`.

**Comment by Hongbo-Miao** [comment]
@dotansimha I just want to say WOOOW. It saves tons of codes.

[This line](https://github.com/dotansimha/angular2-meteor-with-observables/blob/ngrx/client/imports/demo/products-list.component.ts#L31) you didn't handle `unsubscribe` part in the Effects, can you add that part? Thanks

**Comment by Hongbo-Miao** [comment]
@dotansimha oh, for `Tracker` question, I realize right now it is already reactive by default.
However, a lot of time I want it be NOT reactive.

When you dispatch `ADD_PRODUCT_SUCCESS`, the app gets `PRODUCTS_COLLECTION_UPDATED` immediately and show on the View.
So now is

> ADD_PRODUCT_SUCCESS -> PRODUCTS_COLLECTION_UPDATED

What I want a lot of time is when you dispatch `ADD_PRODUCT_SUCCESS`, it won't dispatch `PRODUCTS_COLLECTION_UPDATED` until I dispatch  `LOAD_PRODUCTS_FROM_COLLECTION` manually.

> ADD_PRODUCT_SUCCESS -> LOAD_PRODUCTS_FROM_COLLECTION (by me) -> PRODUCTS_COLLECTION_UPDATED

**Comment by dotansimha** [comment]
Regarding the non-reactive collection, I guess that we can change the implementation, It's just the difference between registering to the `observe` of the `Mongo.Cursor`. 
I have some thoughts about this:

How to trigger the reload action? I mean, all you get from `MeteorOvservables` is an `Observable` which you can't manually trigger to reload. 
Possible solution is maybe to inherit from RxJS's `Observable` into `ObservableMeteorCollection` (this will also simplify the current implementation that declare and bridge each method of the original `Mongo.Cursor`), and extend it with method like `reload` and maybe even `stop` to provide easy use of unsubscribe.
Maybe the creation can be like this (not completely sure about the implementation, please tell me what you think):

```
// Reactive
let observable : Observable<any> = MyObservableCollection.find({});

// Non-reactive
let observable : Observable<any> = MyObservableCollection.find({}).nonReactive();
// And then, to reload:
observable.reload();
// And, to unsubscribe
observable.stop();
```

Regarding the `Tracker` thing, I think about a Meteor subscription that uses `ReactiveVar` and how to re-create the subscription when needed... It might be a little tricky and we need to think about the implementation and how to keep it simple as possible.

**Comment by Urigo** [comment]
Current progress released as `0.6.3-beta.2`

**Comment by dotansimha** [comment]
@Hongbo-Miao Regarding the unimplemented `unsubscribe` thing... not sure how to approach it, because we do not have access to the return value of the `subscribe` because `@ngrx/effects` is in charge of the `subscribe` call, and I'm not sure how we can get it :( any idea?

**Comment by Tallyb** [comment]
It makes no sense that it is a minor release. Should be 0.7.0-beta.1 no?

**Comment by Urigo** [comment]
@Tallyb makes sense, I'll release the next beta as such

**Comment by Hongbo-Miao** [comment]
@dotansimha your implement of the non-reactive collection is good to me I think.

For `unsubscribe`, I am not clear about

> we do not have access to the return value of the subscribe because @ngrx/effects is in charge of the subscribe call

If you do not use ngrx/effects, how do you `unsubscribe`(Meteor Collection) in your the API right now?

(BTW, please write clear `unsubscribe (RxJS)` or `unsubscribe (Meteor Collection)`, sometimes I don't know which you `unsubscribe` you are talking about)

**Comment by dotansimha** [comment]
Yeah sure, sorry about the confusion.

If you use without `effects` you need to do:
```
// This will return Observable
let observable = MeteorObservable.subscribe("mySub");
// This will return the actual Subscription
let subscription = observable.subscribe(...);

// And to destroy it, you can use:
subscription.unsubscribe(); // This will trigger the SubscriptionHandle.stop() of Meteor
```

But if you use `effects`, you do not have access to the `Subscription` object (the one we get from `let subscription = ...`, so you do not have the variable to call `unsubscribe` on. 
You have an `Observable` object in the variable you put the `@Effect` decorator on, but I tried to call `unsubscribe` on that, and it did not call the `unsubscribe` of the relevant Subscription that we need. 

Any idea?

**Comment by Hongbo-Miao** [comment]
@dotansimha if Meteor has an API, `Meteor.unsubscribe('products')`, everything will be easy... You can implement a `MeteorObservable.unsubscribe('products')`.

Let me ask some help from ngrx. Maybe there is way.

**Comment by dotansimha** [comment]
@Hongbo-Miao that's not good... As far as I know, Meteor does not have `Meteor.unsubscribe`, also, you can subscribe to the same publication multiple times with another arguments.
I can keep the Meteor's SubscriptionHandler and expose `unsubscribe` of our own, but I think that we should stick to find a solution using RxJS or ngrx... 

All that we need is to get access to the actual Subscription object that `switchMap` gets...

I am trying now to wrap RxJS `Observable` in order to provide `nonReactive`, `stop` and `reload`.

**Comment by dotansimha** [comment]
@Hongbo-Miao please refer to my new PR: https://github.com/Urigo/angular2-meteor/pull/362

**Comment by Tallyb** [comment]
@dotansimha  @Hongbo-Miao  I am wondering if what you call reactive and non reactive observables, is in fact hot and cold observables, and if the solution described here https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/creating.md can be of help.

**Comment by dotansimha** [comment]
@Tallyb , did not think about the hot and cold. it might solve the issue the force you to run "subscribe" for the return value of "call" and "subscribe". 
I will take a look at this now. 
Thanks!

**Comment by denodaeus** [comment]
One of the biggest issues I have with this (and this seems to be a growing problem in general now that Meteor is trying to support multiple view libraries and npm) is that by creating a new type called MongoObservable, you've removed ecosystem support for things like SimpleSchema (object validation is a critical piece to any not-small-todos-like-app).

You'll probably want to re-tailor MongoObservable to behave like a default Mongo.Collection if you want to have any widespread usage to this.  I like the idea, but I hate that in order to use this it breaks a bunch of other stuff.

**Comment by dotansimha** [comment]
@denodaeus I don't understand why you have issue with that. 

Your collection is still the same, create it:
```
let observableCollection = new MongoObservable.Collection(...);
let theMongoCollection = observableCollection.getMongoCollection();
// now attach you schema to the theMongoCollection
```

And then you have a wrapped collection, and your cursors will look the same...

**Comment by denodaeus** [comment]
Yep I just realized that by looking at your changes, see edited note on my comment above.

Thanks for the awesome updates, one more step closer to a testable angular2-meteor app :)

**Comment by stefanholzapfel** [comment]
Hi!

I have a question concerning performance.

If I subscribe to the MeteorObservable like in your example products.service in the constructor:

```
  constructor() {
    this.data = ProductsCollection.find({});
    MeteorObservable.subscribe("products").subscribe();
  }
```
AND this service is injected in the root injector (e.g. because it provides data needed in serveral modules). In this case, isn't the subscribe "hot" all the time and consuming ressources on server and client?

What is your recommended best practice? Always inject "data"services only local to the component which is in need of the data? Or write "initialize" and "stop" methods in which the MeteorObservable subscritions are started and stopped?

**Comment by dotansimha** [comment]
@stefanholzapfel 
Yeah that's correct. 
You can either create a function in the service that subscribes to the Meteor subscription and then call it when you want to do the actual subscription, or you can use `ngrx` package to create a flow that subscribes only when you need to (take a look at the examples [here](https://github.com/dotansimha/angular2-meteor-with-observables/tree/ngrx))

**Comment by stefanholzapfel** [comment]
Cool thx.

As far as I now, stopping a meteor subscription would normally delete any coresponding documents in clients minimongo. Do you now if it's possible to leave that data as a "cache" in the minimongo? Maybe even after browser restarts?

**Comment by stefanholzapfel** [comment]
Hey guys!

Sorry for bothering you again, this is my next try of an implementation of a global data service:

```
@Injectable()
export class ItemService {

    private itemParameters = {
        find: {},
        options: {limit: 10}
    };
    private itemObservable: ObservableMeteorSubscription;

    constructor() { }

    public stopSync() : void {
        this.itemObservable.stop();
    }

    public getItems(limit?: number) : Observable<Item[]> {
        if (limit) {
            this.itemParameters.options = {limit: limit};
        }
        const newItemObservable = MeteorObservable.subscribe('item', this.itemParameters);
        newItemObservable.subscribe();
        if (this.itemObservable) {
            this.itemObservable.stop();
        }
        this.itemObservable = newItemObservable;
        return itemCollection.find({});
    }
}
```

Do you think that is a reasonable approach?

I was particularly wondering, if it makes a difference whether I first subscribe to the publication with the new parameters and afterwards stop the old subscription or if the order doesn't matter at all? My naive assumption was, that if I first subscribe with the new parameters, the "overlapping" records in the minimongo wouldn't be deleted when stopping the old subscription and I wouldn't have to reload them?

Thanks very much!!

**Comment by barbatus** [comment]
@stefanholzapfel In this case the order doesn't matter (actually stopping is even not needed here).  Meteor is smart enough to recognize that same subscription is made with different params to stop the previous one.

**Comment by stefanholzapfel** [comment]
You're sure? I have tried out to subscribe with a limit of 10, afterwards (without canceling first subscription) I subscribed with a limit of 5, and server side changes (with mongo cli) on records with ranks higher than 5 in the document were still reflected to minimongo...

**Comment by barbatus** [comment]
Ok, this seems to work only when a subscription is wrapped in the autorun (https://guide.meteor.com/data-loading.html#changing-arguments). 
This is what happens when you re-subscribe https://guide.meteor.com/data-loading.html#publication-behavior-with-arguments. I think the order doesn't matter much when to stop the previous.

**Comment by stefanholzapfel** [comment]
Thx, my hope was to get along without making the service a MeteorComponent :)

**Comment by barbatus** [comment]
Well, it's MeteorComponent because it's for components, since it implements OnDestroy and run ngZone on callbacks.  In case everything else, I don't see why it shouldn't be done with direct Meteor API, it's just same as MeteorComponent's one. Observables should be helpful when you use ngrx for example, for other case it is not always true.

**Comment by stefanholzapfel** [comment]
When I try to apply an options object on the MongoObservable.Collection<Item>('item').find() method, I get an error.

`MongoObservable.Collection<Item>('item').find({}, {})` 
works, but returns ALL elements in the local minimongo-db which is not always what I want

e.g.
`MongoObservable.Collection<Item>('item').find({}, { limit: 10 })`
throws me: 
"Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit"

**Comment by jalalat** [comment]
I posted one issue last month nobody replied to that. Can any of you please check if i doing anything wrong: https://github.com/dotansimha/angular2-meteor-with-observables/issues/9

**Pull request merged**
