### PR TITLE
Add support for Meteor 1.3 with NPM

### PR DESCRIPTION
**Pull request by dotansimha**
@Urigo @barbatus 

Read the https://github.com/Urigo/angular2-meteor/blob/60ed004efbc0517dbc40f5a6cf96c3f1fbe57f72/CHANGELOG.md of this branch for more information. 

There are some more TODOs, but this is a basic working version.

Created the PR for Travis to run the tests. 

Still missing in this PR:
- Export the `packages` to external NPM modules (Also, check about multiple NPM modules in the same repo - I think we need it to keep things in place).
- Examples.
- Angular2-Meteor-Auto-Bootstrap.
- Finish with the README file.
- Maybe use WebPack?

### CODE REVIEW

**Comment by barbatus** [comment]
How about to merge it in to the master when Meteor 1.3 comes out?
I am still updating Tutorial and would like to change/keep old version yet.

**Comment by dotansimha** [comment]
@barbatus yeah sure we should not merge it yet.. actually opened in to test if everything works in the CI, but then I noticed that there it no CI for this repo yet...

**Comment by barbatus** [comment]
Yep, I tried to add Travis long time ago, but turned out hadn't enough permissions.

**Comment by Urigo** [comment]
I'll add the CI today.
We can leave the PR open until Meteor 1.3 will be out. @barbatus is doing lots of work on the current version and I don't want to hold him back until 1.3 is out

**Pull request merged**
